### PR TITLE
Fix loader not returning a function when used with latest webpack

### PR DESCRIPTION
**Pull request by luigiplr**
Also bring up to es6 spec.

### CODE REVIEW

**Comment by dminkovsky** [comment]
Thank you! Let me take a look!

**Comment by dminkovsky** [comment]
Hey this is a looks great, thank you. I'm wondering though, regarding:

> Fix loader not returning a function when used with latest webpack 

I'm not seeing what among these changes addresses "returning a function", perhaps because I'm not sure what you mean by that.

**Comment by luigiplr** [comment]
> I'm not seeing what among these changes addresses "returning a function", perhaps because I'm not sure what you mean by that.

Modified from: 
`content[0] = 'exports = module.exports = require("css-loader/lib/css-base.js")();';`
To: 
`content[0] = 'exports = require("css-loader/lib/css-base.js")()'` 

As evaling it was overriding the default `module.exports` from babel transforming `default export`

See below:

**Comment by dminkovsky** [comment]
Oh that's interesting. I'll merge of course, but just wanted to understand this patch. Thank you.

So, this only happens with the `webpack.config.babel.js` ("native" babel support), right? I think they added that after I made this plugin.

**Comment by dminkovsky** [comment]
Just published.

**Comment by luigiplr** [comment]
> So, this only happens with the webpack.config.babel.js ("native" babel support), right?

Yep :smile: 

> Just published.

Awesome; thanks!!

**Pull request merged**
